client:
  build: ./client
  volumes:
    - ./client/app/:/kindlized-client/app
    - ./server/public/:/kindlized-client/public

database:
  build: ./database

server:
  build: ./server
  command: 'npm start'
  volumes:
    - ./server/:/kindlized-server
  ports:
    - "3000:3000"
  links:
    - database
  volumes_from:
    - client
#     - bundle
#
# bundle:
#   image: busybox
#   volumes:
#     - /bundle
