client:
  build: ./client

mongod:
  build: ./mongod
  ports:
    - "27017:27017"

redis:
  image: redis:3.0.7
  ports:
    - "6379:6379"

server:
  build: ./server
  ports:
    - "80:3000"
  links:
    - mongod
    - redis
  environment:
  - KINDLIZED_AWS_ACCESS_KEY_ID=${KINDLIZED_AWS_ACCESS_KEY_ID}
  - KINDLIZED_AWS_SECRET_KEY_ID=${KINDLIZED_AWS_SECRET_KEY_ID}
  - KINDLIZED_AWS_SSSOCIATES_ID=${KINDLIZED_AWS_SSSOCIATES_ID}
  - KINDLIZED_TW_CONSUMER_KEY=${KINDLIZED_TW_CONSUMER_KEY}
  - KINDLIZED_TW_CONSUMER_SECRET=${KINDLIZED_TW_CONSUMER_SECRET}
  - KINDLIZED_TW_CALLBACK=${KINDLIZED_TW_CALLBACK}
  - KINDLIZED_TW_ACCESS_TOKEN=${KINDLIZED_TW_ACCESS_TOKEN}
  - KINDLIZED_TW_ACCESS_TOKEN_SECRET=${KINDLIZED_TW_ACCESS_TOKEN_SECRET}
  - KINDLIZED_GMAIL_USER=${KINDLIZED_GMAIL_USER}
  - KINDLIZED_GMAIL_PASSWORD=${KINDLIZED_GMAIL_PASSWORD}
  - KINDLIZED_MANDRILL=${KINDLIZED_MANDRILL}
  - KINDLIZED_SLACK=${KINDLIZED_SLACK}
  - KINDLIZED_SESSION=${KINDLIZED_SESSION}
  - KINDLIZED_MONGODB=mongodb://${DOCKER_IP}:27017/kindlized
  - DOCKER_IP=${DOCKER_IP}
  command: ['npm', 'run', 'pm2:start']
  restart: always

