client:
  extends:
    file: docker-compose.yml
    service: client
  command: ['npm', 'run', build]

database:
  extends:
    file: docker-compose.yml
    service: database

server:
  build: ./server
  ports:
    - "80:3000"
  links:
    - database
  environment:
  - KINDLIZED_AWS_ACCESS_KEY_ID=${KINDLIZED_AWS_ACCESS_KEY_ID}
  - KINDLIZED_AWS_SECRET_KEY_ID=${KINDLIZED_AWS_SECRET_KEY_ID}
  - KINDLIZED_AWS_SSSOCIATES_ID=${KINDLIZED_AWS_SSSOCIATES_ID}
  - KINDLIZED_TW_CONSUMER_KEY=${KINDLIZED_TW_CONSUMER_KEY}
  - KINDLIZED_TW_CONSUMER_SECRET=${KINDLIZED_TW_CONSUMER_SECRET}
  - KINDLIZED_TW_CALLBACK=${KINDLIZED_TW_CALLBACK}
  - KINDLIZED_TW_ACCESS_TOKEN=${KINDLIZED_TW_ACCESS_TOKEN}
  - KINDLIZED_TW_ACCESS_TOKEN_SECRET=${KINDLIZED_TW_ACCESS_TOKEN_SECRET}
  - KINDLIZED_GMAIL_USER=${KINDLIZED_GMAIL_USER}
  - KINDLIZED_GMAIL_PASSWORD=${KINDLIZED_GMAIL_PASSWORD}
  - KINDLIZED_MANDRILL=${KINDLIZED_MANDRILL}
  - KINDLIZED_SLACK=${KINDLIZED_SLACK}
  - KINDLIZED_SESSION=${KINDLIZED_SESSION}
  - KINDLIZED_MONGODB=mongodb://${DOCKER_IP}:27017/kindlized
  volumes_from:
    - client
